name: .NET

on:
  push:
    branches:
      - main
      - dev
      - hw01
  pull_request:
    branches:
      - main
      - dev
      - hw01

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build in Debug mode
        run: dotnet build --no-restore
      - name: TestsCSharp 
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings ../.github/coverlet.runsettings
        working-directory: Tests.CSharp
      - name: TestsFSharp
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings ../.github/coverlet.runsettings
        working-directory: Tests.FSharp
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build in Debug mode
        run: dotnet build
      - name: TestsCSharp
        run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-build
        working-directory: Tests.CSharp
      - name: TestsFSharp
        run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-build
        working-directory: Tests.FSharp
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: 'Tests.*Sharp/TestResults/*.trx'
